### ISSUE TITLE
Jenkins pod times out DeploymentConfig waiting for plugin updates

### ISSUE THREAD

**Issue by adamgoossens** [ploigos/ploigos-software-factory-operator#120]
On startup the Jenkins pod will attempt to update all of the plugins installed within the container. This often takes longer than the 600 seconds that the Jenkins DeploymentConfig specifies as its `spec.strategy.recreateParams.timeoutSeconds`, particularly if the upstream internet connection is slow (like mine...).

One option is to disable plugin updates entirely using the JENKINS_JAVA_OVERRIDES environment variable in the DC with `-Dhudson.model.UpdateCenter.never=true`. This means that whatever the plugin versions were when the Jenkins OCP4 image was cut, is what are used. This may not be a bad idea if we want to 'freeze' the pipeline components in time to ensure they're all a known quantity.

Another option could be to just to ramp up the `timeoutSeconds` parameter, creating something particularly generous (e.g. 60 minutes). That can result in a long setup time for the Platform.

I'm partial to the first option, although simply saying "don't update on startup" would be better.

(Edit: had the wrong override)

**Comment by andykrohg** [comment]
I agree that it would be preferable to disable plugin updates, as we'll eventually need a strategy for deployments in disconnected environments. However, the `TsscPipeline` currently relies on the plugins specified in the `DeploymentConfig` in the `INSTALL_PLUGINS` environment variable. We considered cutting our own image with those plugins pre-installed, but that puts us in a precarious position regarding support from the BU. At the moment, the path of least resistance may be to simply increase the timeout.

**Comment by adamgoossens** [comment]
I did some more testing, and it looks like the plugins are still installed even when plugin updates are disabled. Perhaps we can disable the updates after all (+ bump the timeout for good measure anyway?)

Regarding the install plugins, perhaps we can side-load them: 

1. Bundle them up in a minimal container (e.g. jenkins-ploigos-plugins)
2. Ploigos operator adds jenkins-ploigos-plugins as an init container to the Jenkins pod + attaches the PV.
3. Entrypoint is a basic script that copies the plugins to the Jenkins PV.
4. Init container terminates, Jenkins starts up, plugins are already present. `INSTALL_PLUGINS` can be removed.

If that works we could ship a known set of plugins into disconnected environments and still keep the separation with the BU-provided image. Totally theoretical though...

**Comment by andykrohg** [comment]
I love it. What do you think of them apples @jflowers ?

**Comment by jflowers** [comment]
That's perfect! It will also solve for disconnected...

**Comment by adamgoossens** [comment]
Ok, let me run a test to see if side-loading is viable and in the interim I can do a PR to disable plugin updates (perhaps we can make that configurable via an option on the Platform CRD).

**Comment by andykrohg** [comment]
I think disabling updates is valuable once we get side-loading working, but until then, doing so would simply break things since the Platform isn't usable without the required plugins.

**Comment by adamgoossens** [comment]
Sounds good :) I'll focus only on the side-loading test then. Hopefully it's simple and straight forward. How hard can it be?

**Comment by adamgoossens** [comment]
https://github.com/ploigos/ploigos-containers/pull/54 has been raised.

As it turns out we don't need the `-Dhudson.model.UpdateCenter.never=true` property...turns out I was just getting confused with how the `/usr/libexec/s2i/run` script operates in the Jenkins base image. If we can side-load the plugins the problem disappears.

**Comment by andykrohg** [comment]
This is OBE, since we're now using an init container to sideload plugins as discussed above
