### ISSUE TITLE
Keycloak Postgres POD missing

### ISSUE THREAD

**Issue by mike4263** [ploigos/ploigos-software-factory-operator#127]
Tried spinning this up from the instructions.

Keycloak POD fails to come up with the following error:
```
Caused by: org.postgresql.util.PSQLException: Connection to keycloak-postgresql.devsecops.svc.cluster.local:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

The keycloak-postgresql service does not have a pod selector attached to it.

```
  selector:
    name: rhsso-postgresql
```

Also, the Postgres env var in the stateful set is pointed at keycloak not rhsso.  There seems to be a mix of keycloak/rhsso throughout.

**Comment by mike4263** [comment]
gitea also fails to come up because of this issue

**Comment by mike4263** [comment]
I just spun up the rhsso operator directly (version 7.4.5) in another namespace, and it uses "keycloak" as the name throughout.  

I believe we can modify the Keycloak object with this and remove our custom Postgres provisioning code:

```
  selector:
    name: rhsso-postgresql
```

**Comment by andykrohg** [comment]
This issue has been resolved by using the postgres deployment provided by the rhsso operator in lieu of spinning one up ourselves
