### ISSUE TITLE
Make it easier for the user to know what CI Tools / Container Registry are supported

### ISSUE THREAD

**Issue by garethahealy** [ploigos/ploigos-software-factory-operator#160]
As a first time user, I am unsure what CI Tool options can be set. When using the web console, its a free-text box:

<img width="767" alt="Screenshot 2021-03-18 at 15 36 12" src="https://user-images.githubusercontent.com/8656974/111653536-ea2a8f00-87ff-11eb-9171-00ecc12304be.png">

Looking in the docs doesn't help much either, as I can't see a list that says what's supported:
- https://ploigos.github.io/ploigos-docs/

The only way to find out what the options are is by looking at the code:
- https://github.com/ploigos/ploigos-software-factory-operator/blob/e03b161ba6a40e6c414065fd3d37f7d81b0591ac/roles/tssc-platform/deployment/tasks/main.yml#L57-L63

**Comment by garethahealy** [comment]
The same goes for the container registry. Nexus is the default, but looking in the ansible, can see quay is supported as well.

**Comment by andykrohg** [comment]
I've updated the CRD to specify the default value as well as the list of supported alternatives for both providers 👍 https://github.com/ploigos/ploigos-software-factory-operator/blob/main/config/crd/bases/redhatgov.io_tsscplatforms.yaml#L60. This should be reflected in version 0.2.7.
