### ISSUE TITLE
CRD TsscPipeline

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#21]
Implement CRD for TsscPipeline

actions:
- create an org in gitea
- create or import a repo into the org
- create a team in the org
- etc... as per the Google Doc 'TISC/TSSC Disconnected Environment Installation Guide' and https://github.com/rhtconsulting/tssc-infra

add options:
- ???

This supports the use case for both demo of TSSC with a reference app as well as a production deployment.

If importing a reference app this should result in a fully functional pipeline without the need for addition steps

**Comment by andykrohg** [comment]
Done
