### ISSUE TITLE
RHSSO lookup passwords should be put in secrets

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#25]
Before or after #12 address this:

https://github.com/RedHatGov/devsecops-workshop-code/blob/rhedsord/roles/rhsso/defaults/main.yml#L16

we should be putting this in a secret and looking for it in that secret

1. lookup password from file and put in a trash var solely for use in the next step
1. put it in a secret unless the secret already exists
1. pull value from secret into var that other tasks use

without this the password temp file is lost when the operator pod is recreated and the operator is no longer able to function

**Comment by david-rh** [comment]
This password is generated for the PostgreSQL database that is used by RH-SSO. It is stored in a secret used by the PostgreSQL deployment.

https://github.com/RedHatGov/devsecops-workshop-code/blob/rhedsord/roles/rhsso/templates/rhsso-postgresql.yml.j2#L9

**Comment by andykrohg** [comment]
Done
