### ISSUE TITLE
Quay Configuration (org,accounts,etc) need  managed by TSSC operator

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#43]
- Create robot account for TSSC pipeline to use and store creds in an image pull secret for Jenkins to use, name it quay-basic-auth
- Create or identify an account to own the organization where the pipeline will put it's repo. If it's a new user store the creds in a secret
- Create the org for the pipeline to put it's repo
- Create the repo because I think it need to be public

**Comment by andykrohg** [comment]
Done
